-- *************************************************************************************
-- Alter table special request

ALTER TABLE "CART_REQUEST_TOOL"."SPECIAL_REQUEST" ADD ("ITEM" INTEGER);
ALTER TABLE "CART_REQUEST_TOOL"."SPECIAL_REQUEST" ADD ("START_DATE" TIMESTAMP);
ALTER TABLE "CART_REQUEST_TOOL"."SPECIAL_REQUEST" ADD ("END_DATE" TIMESTAMP);
ALTER TABLE "CART_REQUEST_TOOL"."SPECIAL_REQUEST" ADD ("UNIT_PRICE" DECIMAL(19,2));
ALTER TABLE "CART_REQUEST_TOOL"."SPECIAL_REQUEST" ADD ("QUANTITY" INTEGER);
ALTER TABLE "CART_REQUEST_TOOL"."SPECIAL_REQUEST" ADD ("CURRENCY_ID" BIGINT);
ALTER TABLE "CART_REQUEST_TOOL"."SPECIAL_REQUEST" ADD ("UNIT" NVARCHAR(255));
ALTER TABLE "CART_REQUEST_TOOL"."SPECIAL_REQUEST" ADD ("AMOUNT" DECIMAL(19,2));
ALTER TABLE "CART_REQUEST_TOOL"."SPECIAL_REQUEST" ADD ("BUDGET" DECIMAL(19,2));
ALTER TABLE "CART_REQUEST_TOOL"."SPECIAL_REQUEST" ADD ("VENDOR_TEXT" NVARCHAR(1000));

-- *************************************************************************************
-- Update schema version

INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT) 
VALUES('V2.0.0-51', 'Alter Special Request', 'V201706261530__Alter_special_request.sql');

COMMIT;