/* MESSAGE TABLES MIGRATION TO SUPPORT ADDITIONAL_MESSAGE_TYPE_INFORMATION AND ADDITIONAL_ISSUE_TYPE_INFORMATION */

-- *************************************************************************************
/* RENAME all column references to the modified tables */

	-- CHANGE_VENDOR_REQUEST_MESSAGE
RENAME COLUMN "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST_MESSAGE".RETURN_TYPE_ID to MESSAGE_TYPE_ID;
RENAME COLUMN "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST_MESSAGE".ISSUE_TYPE_ID to SUBJECT_ID;
RENAME COLUMN "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST_MESSAGE".ADDITIONAL_RETURN_TYPE_INFORMATION to ADDITIONAL_MESSAGE_TYPE_INFORMATION;
RENAME COLUMN "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST_MESSAGE".ADDITIONAL_ISSUE_TYPE_INFORMATION to ADDITIONAL_SUBJECT_INFORMATION;
	-- EXTEND_VENDOR_REQUEST_MESSAGE
RENAME COLUMN "CART_REQUEST_TOOL"."EXTEND_VENDOR_REQUEST_MESSAGE".RETURN_TYPE_ID to MESSAGE_TYPE_ID;
RENAME COLUMN "CART_REQUEST_TOOL"."EXTEND_VENDOR_REQUEST_MESSAGE".ISSUE_TYPE_ID to SUBJECT_ID;
RENAME COLUMN "CART_REQUEST_TOOL"."EXTEND_VENDOR_REQUEST_MESSAGE".ADDITIONAL_RETURN_TYPE_INFORMATION to ADDITIONAL_MESSAGE_TYPE_INFORMATION;
RENAME COLUMN "CART_REQUEST_TOOL"."EXTEND_VENDOR_REQUEST_MESSAGE".ADDITIONAL_ISSUE_TYPE_INFORMATION to ADDITIONAL_SUBJECT_INFORMATION;
	-- INQUIRY_MESSAGE
RENAME COLUMN "CART_REQUEST_TOOL"."INQUIRY_MESSAGE".RETURN_TYPE_ID to MESSAGE_TYPE_ID;
ALTER TABLE "CART_REQUEST_TOOL"."INQUIRY_MESSAGE" ADD ("SUBJECT_ID" BIGINT);
ALTER TABLE "CART_REQUEST_TOOL"."INQUIRY_MESSAGE" ADD ("ADDITIONAL_MESSAGE_TYPE_INFORMATION" NVARCHAR(255));
ALTER TABLE "CART_REQUEST_TOOL"."INQUIRY_MESSAGE" ADD ("ADDITIONAL_SUBJECT_INFORMATION" NVARCHAR(255));
	-- REQUEST_MESSAGE
RENAME COLUMN "CART_REQUEST_TOOL"."REQUEST_MESSAGE".RETURN_TYPE_ID to MESSAGE_TYPE_ID;
RENAME COLUMN "CART_REQUEST_TOOL"."REQUEST_MESSAGE".ISSUE_TYPE_ID to SUBJECT_ID;
RENAME COLUMN "CART_REQUEST_TOOL"."REQUEST_MESSAGE".ADDITIONAL_RETURN_TYPE_INFORMATION to ADDITIONAL_MESSAGE_TYPE_INFORMATION;
RENAME COLUMN "CART_REQUEST_TOOL"."REQUEST_MESSAGE".ADDITIONAL_ISSUE_TYPE_INFORMATION to ADDITIONAL_SUBJECT_INFORMATION;
	-- VENDOR_REQUEST_MESSAGE
RENAME COLUMN "CART_REQUEST_TOOL"."VENDOR_REQUEST_MESSAGE".RETURN_TYPE_ID to MESSAGE_TYPE_ID;
RENAME COLUMN "CART_REQUEST_TOOL"."VENDOR_REQUEST_MESSAGE".ISSUE_TYPE_ID to SUBJECT_ID;
RENAME COLUMN "CART_REQUEST_TOOL"."VENDOR_REQUEST_MESSAGE".ADDITIONAL_RETURN_TYPE_INFORMATION to ADDITIONAL_MESSAGE_TYPE_INFORMATION;
RENAME COLUMN "CART_REQUEST_TOOL"."VENDOR_REQUEST_MESSAGE".ADDITIONAL_ISSUE_TYPE_INFORMATION to ADDITIONAL_SUBJECT_INFORMATION;
	-- VENDOR_INQUIRY_MESSAGE
RENAME COLUMN "CART_REQUEST_TOOL"."VENDOR_INQUIRY_MESSAGE".RETURN_TYPE_ID to MESSAGE_TYPE_ID;
RENAME COLUMN "CART_REQUEST_TOOL"."VENDOR_INQUIRY_MESSAGE".ISSUE_TYPE_ID to SUBJECT_ID;
RENAME COLUMN "CART_REQUEST_TOOL"."VENDOR_INQUIRY_MESSAGE".ADDITIONAL_RETURN_TYPE_INFORMATION to ADDITIONAL_MESSAGE_TYPE_INFORMATION;
RENAME COLUMN "CART_REQUEST_TOOL"."VENDOR_INQUIRY_MESSAGE".ADDITIONAL_ISSUE_TYPE_INFORMATION to ADDITIONAL_SUBJECT_INFORMATION;

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT) 
VALUES('V2.0.0-36', 'Alter MESSAGE tables, Rename RETURN_TYPE and ISSUE_TYPE by MESSAGE_TYPE and SUBECT', 'V201704101350__Alter_message_tables.sql');

COMMIT;