-- *************************************************************************************
/* New columns in RETURN_TYPE & ISSUE_TYPE tables */
-- *************************************************************************************
	/* RETURN TYPE */
alter table "CART_REQUEST_TOOL"."RETURN_TYPE" add ("ADDITIONAL_RETURN_TYPE_INFORMATION" TINYINT DEFAULT 0)
	/* ISSUE TYPE */
alter table "CART_REQUEST_TOOL"."ISSUE_TYPE" add ("ADDITIONAL_ISSUE_TYPE_INFORMATION" TINYINT DEFAULT 0)

/* New columns in MESSAGE tables */

	/* VENDOR REQUEST MESSAGE */
alter table "CART_REQUEST_TOOL"."VENDOR_REQUEST_MESSAGE" add("ADDITIONAL_RETURN_TYPE_INFORMATION" NVARCHAR(255) NULL);
alter table "CART_REQUEST_TOOL"."VENDOR_REQUEST_MESSAGE" add("ADDITIONAL_ISSUE_TYPE_INFORMATION" NVARCHAR(255) NULL);

	/* CHANGE VENDOR REQUEST MESSAGE */
alter table "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST_MESSAGE" add("ADDITIONAL_RETURN_TYPE_INFORMATION" NVARCHAR(255) NULL)
alter table "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST_MESSAGE" add("ADDITIONAL_ISSUE_TYPE_INFORMATION" NVARCHAR(255) NULL)

	/* EXTEND VENDOR REQUEST MESSAGE */
alter table "CART_REQUEST_TOOL"."EXTEND_VENDOR_REQUEST_MESSAGE" add("ADDITIONAL_RETURN_TYPE_INFORMATION" NVARCHAR(255) NULL);
alter table "CART_REQUEST_TOOL"."EXTEND_VENDOR_REQUEST_MESSAGE" add("ADDITIONAL_ISSUE_TYPE_INFORMATION" NVARCHAR(255) NULL);

	/* VENDOR INQUIRY MESSAGE */
alter table "CART_REQUEST_TOOL"."VENDOR_INQUIRY_MESSAGE" add("ADDITIONAL_RETURN_TYPE_INFORMATION" NVARCHAR(255) NULL);
alter table "CART_REQUEST_TOOL"."VENDOR_INQUIRY_MESSAGE" add("ADDITIONAL_ISSUE_TYPE_INFORMATION" NVARCHAR(255) NULL);

	/* INQUIRY MESSAGE */
alter table "CART_REQUEST_TOOL"."INQUIRY_MESSAGE" add ("ISSUE_TYPE_ID" INTEGER null default 0)
alter table "CART_REQUEST_TOOL"."INQUIRY_MESSAGE" add("ADDITIONAL_RETURN_TYPE_INFORMATION" NVARCHAR(255) NULL);
alter table "CART_REQUEST_TOOL"."INQUIRY_MESSAGE" add("ADDITIONAL_ISSUE_TYPE_INFORMATION" NVARCHAR(255) NULL);

	/* REQUEST MESSAGE */
RENAME COLUMN "CART_REQUEST_TOOL"."REQUEST_MESSAGE".OTHER_ISSUE_TYPE to ADDITIONAL_ISSUE_TYPE_INFORMATION;
alter table "CART_REQUEST_TOOL"."REQUEST_MESSAGE" add("ADDITIONAL_RETURN_TYPE_INFORMATION" NVARCHAR(255) NULL);

-- *************************************************************************************
/* Permissions */
-- *************************************************************************************

	/* Return type */
INSERT INTO "CART_REQUEST_TOOL"."PERMISSION_SERVICE"(PERMISSION_SERVICE_ID, SERVICE_NAME, PERMISSION_ID, RESOURCE_ID,CREATED_USER_ID) values(188,'returnTypeService',10,6,1);
INSERT INTO "CART_REQUEST_TOOL"."PERMISSION_SERVICE"(PERMISSION_SERVICE_ID, SERVICE_NAME, PERMISSION_ID, RESOURCE_ID,CREATED_USER_ID) values(189,'returnTypeService',11,6,1);
	/* Issue type */
INSERT INTO "CART_REQUEST_TOOL"."PERMISSION_SERVICE"(PERMISSION_SERVICE_ID, SERVICE_NAME, PERMISSION_ID, RESOURCE_ID,CREATED_USER_ID) values(190,'issueTypeService',10,6,1);
INSERT INTO "CART_REQUEST_TOOL"."PERMISSION_SERVICE"(PERMISSION_SERVICE_ID, SERVICE_NAME, PERMISSION_ID, RESOURCE_ID,CREATED_USER_ID) values(191,'issueTypeService',11,6,1);

-- *************************************************************************************
-- Update schema version

INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT) 
VALUES('V2.0.0-33', 'Alter Message table, Return type table and Issue type table - Added Create/Edit & Delete permissions', 'V201703301630__Alter_message_returnType_issueType_tables_and_permissions.sql');

COMMIT;