-- *************************************************************************************
-- Create table MESSAGE_TYPE_PERMISSION

CREATE COLUMN TABLE "CART_REQUEST_TOOL"."MESSAGE_TYPE_PERMISSION"
(
	MESSAGE_TYPE_PERMISSION_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	ROLE_ID BIGINT NOT NULL,
	RESOURCE_ID BIGINT NOT NULL,
	PERMISSION_ID BIGINT NOT NULL,
	
	CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE_TZ TIMESTAMP,
	CREATED_USER_ID BIGINT NOT NULL,
	MODIFIED_USER_ID BIGINT,
	ENABLED TINYINT DEFAULT 1, 
	DELETED TINYINT DEFAULT 0
);

ALTER TABLE "CART_REQUEST_TOOL"."MESSAGE_TYPE_PERMISSION" ADD FOREIGN KEY ( "ROLE_ID" ) REFERENCES "CART_REQUEST_TOOL"."ROLE" ("ROLE_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;

ALTER TABLE "CART_REQUEST_TOOL"."MESSAGE_TYPE_PERMISSION" ADD FOREIGN KEY ( "RESOURCE_ID" ) REFERENCES "CART_REQUEST_TOOL"."RESOURCE" ("RESOURCE_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;

ALTER TABLE "CART_REQUEST_TOOL"."MESSAGE_TYPE_PERMISSION" ADD FOREIGN KEY ( "PERMISSION_ID" ) REFERENCES "CART_REQUEST_TOOL"."PERMISSION" ("PERMISSION_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;

ALTER TABLE "CART_REQUEST_TOOL"."MESSAGE_TYPE_PERMISSION" ADD FOREIGN KEY ( "CREATED_USER_ID" ) REFERENCES "CART_REQUEST_TOOL"."USER" ("USER_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;


-- *************************************************************************************
-- Insert permission for superadmin role

INSERT INTO "CART_REQUEST_TOOL"."MESSAGE_TYPE_PERMISSION"(role_id, resource_id, permission_id, enabled, created_user_id) 
 	VALUES(1, 2, 10, 1, 1);
INSERT INTO "CART_REQUEST_TOOL"."MESSAGE_TYPE_PERMISSION"(role_id, resource_id, permission_id, enabled, created_user_id) 
 	VALUES(1, 3, 10, 1, 1);
INSERT INTO "CART_REQUEST_TOOL"."MESSAGE_TYPE_PERMISSION"(role_id, resource_id, permission_id, enabled, created_user_id) 
 	VALUES(1, 7, 10, 1, 1);
INSERT INTO "CART_REQUEST_TOOL"."MESSAGE_TYPE_PERMISSION"(role_id, resource_id, permission_id, enabled, created_user_id) 
 	VALUES(1, 13, 10, 1, 1);
 	
-- *************************************************************************************
-- Insert permission for superadmin role

INSERT INTO "CART_REQUEST_TOOL"."MESSAGE_TYPE_PERMISSION"(role_id, resource_id, permission_id, enabled, created_user_id) 
 	VALUES(3, 2, 10, 1, 1);
INSERT INTO "CART_REQUEST_TOOL"."MESSAGE_TYPE_PERMISSION"(role_id, resource_id, permission_id, enabled, created_user_id) 
 	VALUES(3, 3, 10, 1, 1);
INSERT INTO "CART_REQUEST_TOOL"."MESSAGE_TYPE_PERMISSION"(role_id, resource_id, permission_id, enabled, created_user_id) 
 	VALUES(3, 7, 10, 1, 1);
INSERT INTO "CART_REQUEST_TOOL"."MESSAGE_TYPE_PERMISSION"(role_id, resource_id, permission_id, enabled, created_user_id) 
 	VALUES(3, 13, 10, 1, 1);
 	

-- *************************************************************************************
-- Insert new application version

INSERT INTO "CART_REQUEST_TOOL"."APPLICATION_VERSION"(VERSION, APPLICATION_ID, CREATED_USER_ID, RELEASE_NOTES)
VALUES('2.0.2',1,1,'Created administration to set Message Type special permissions for each resource');


-- *************************************************************************************
-- Update schema version

INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT) 
VALUES('V2.0.0-66', 'Create MESSAGE_TYPE_PERMISSION table and insert permissions for superadmin', 'V201711021150__Create_message_type_permission.sql');

COMMIT;