-- *************************************************************************************
-- Drop Contraints

--STEPS TO DROP VENDOR_ID CONTRAINT IN VENDOR REQUEST INQUIRY TABLES

-- FIRST
--REPLACE <TABLE_NAME> with "EXTEND_VENDOR_REQUEST" or "CHANGE_VENDOR_REQUEST"

-- select CONSTRAINT_NAME from "REFERENTIAL_CONSTRAINTS"
-- where TABLE_NAME = <TABLE_NAME> AND COLUMN_NAME = 'VENDOR_ID'
-- order by COLUMN_NAME;

-- AFTER REPLACE <CONSTRAINT_NAME> WITH CONSTRAINT_NAME
-- delete the constraint from the table:

-- ALTER TABLE <TABLE_NAME> DROP CONSTRAINT <CONSTRAINT_NAME>;

-- *************************************************************************************
-- Create vendor columns

/*VENDOR INQUIRY*/
RENAME COLUMN "CART_REQUEST_TOOL"."VENDOR_INQUIRY".VENDOR_ID to VENDOR_NAME;
ALTER TABLE "CART_REQUEST_TOOL"."VENDOR_INQUIRY" ALTER (VENDOR_NAME nvarchar(255) NULL);

/*CHANGE VENDOR REQUEST*/
RENAME COLUMN "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST".VENDOR_ID to VENDOR_NAME;
ALTER TABLE "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST" ALTER (VENDOR_NAME nvarchar(255) NOT NULL);
ALTER TABLE "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST" ADD ("VENDOR_ACCOUNT" NVARCHAR (255) NULL);
ALTER TABLE "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST" ADD ("VENDOR_CONTACT_NAME" NVARCHAR (255) NULL);
ALTER TABLE "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST" ADD ("VENDOR_CONTACT_EMAIL" NVARCHAR (255) NULL);
ALTER TABLE "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST" ADD ("VENDOR_CONTACT_PHONE" NVARCHAR (255) NULL);

/*EXTEND VENDOR REQUEST*/
RENAME COLUMN "EXTEND_VENDOR_REQUEST".VENDOR_ID TO VENDOR_LEGAL_NAME;
ALTER TABLE "EXTEND_VENDOR_REQUEST" ALTER ("VENDOR_LEGAL_NAME" NVARCHAR(255) NOT NULL);
ALTER TABLE "EXTEND_VENDOR_REQUEST" ADD ("VENDOR_INFORMAL_NAME" NVARCHAR(255) NULL);
ALTER TABLE "EXTEND_VENDOR_REQUEST" ADD ("CONTACT_NAME" NVARCHAR(255) NULL);
ALTER TABLE "EXTEND_VENDOR_REQUEST" ADD ("CONTACT_EMAIL" NVARCHAR(255) NULL);
ALTER TABLE "EXTEND_VENDOR_REQUEST" ADD ("CONTACT_PHONE" NVARCHAR(255) NULL);

-- *************************************************************************************
-- Add mock data to not null columns

--UPDATE table
--set table.VENDOR_NAME = 'Vendor Name'
--from "CART_REQUEST_TOOL"."VENDOR_INQUIRY" table;

--UPDATE table
--set table.VENDOR_ACCOUNT = 'Vendor Account',
--table.VENDOR_CONTACT_NAME = 'Contact Name',
--table.VENDOR_CONTACT_EMAIL = 'contact@email.com'
--from "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST" table;

--UPDATE table
--set table.VENDOR_LEGAL_NAME = 'Vendor Legal Name',
--table.CONTACT_NAME = 'Contact Name',
--table.CONTACT_EMAIL = 'contact@email.com'
--from "CART_REQUEST_TOOL"."EXTEND_VENDOR_REQUEST" table;

-- *************************************************************************************
-- Alter columns to make them not null

/*VENDOR INQUIRY*/
ALTER TABLE "CART_REQUEST_TOOL"."VENDOR_INQUIRY" ALTER (VENDOR_NAME nvarchar(255) NOT NULL);

/*CHANGE VENDOR REQUEST*/
ALTER TABLE "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST" ALTER (VENDOR_ACCOUNT nvarchar(255) NOT NULL);
ALTER TABLE "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST" ALTER (VENDOR_CONTACT_NAME nvarchar(255) NOT NULL);
ALTER TABLE "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST" ALTER (VENDOR_CONTACT_EMAIL nvarchar(255) NOT NULL);

/*EXTEND VENDOR REQUEST*/
ALTER TABLE "EXTEND_VENDOR_REQUEST" ALTER ("CONTACT_NAME" NVARCHAR(255) NOT NULL);
ALTER TABLE "EXTEND_VENDOR_REQUEST" ALTER ("CONTACT_EMAIL" NVARCHAR(255) NOT NULL);

-- *************************************************************************************
-- Update schema version

INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT) 
VALUES('V2.0.0-26', 'Alter Vendor Request / Inquiry tables to add missing vendor information', 'V201703141325__Alter_vendor_inquiry_extend_change.sql');

COMMIT;