UPDATE "CART_REQUEST_TOOL"."ROLE_PERMISSION"
SET PERMISSION_LEVEL = 2
WHERE ROLE_ID = 1
	AND RESOURCE_ID = 3
	AND PERMISSION_ID = 10;

UPDATE "CART_REQUEST_TOOL"."ROLE_PERMISSION"
SET PERMISSION_LEVEL = 2
WHERE ROLE_ID = 1
	AND RESOURCE_ID = 7
	AND PERMISSION_ID = 10;
	
UPDATE "CART_REQUEST_TOOL"."ROLE_PERMISSION"
SET PERMISSION_LEVEL = 2
WHERE ROLE_ID = 3
	AND RESOURCE_ID = 3
	AND PERMISSION_ID = 10;

UPDATE "CART_REQUEST_TOOL"."ROLE_PERMISSION"
SET PERMISSION_LEVEL = 2
WHERE ROLE_ID = 3
	AND RESOURCE_ID = 7
	AND PERMISSION_ID = 10;

-- *************************************************************************************
-- Update schema version

INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT) 
VALUES('V2.0.0-70', 'Insert special permission to SuperAdmin and Business Mgr. roles in ROLE_PERMISSION table', 'V201711280830__Insert_special_role_permission_inquiry_vendor_request.sql');

COMMIT;