/* Remove column 'MESSAGE_CONTENT_BKP' from all tables */

ALTER TABLE "CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST_MESSAGE" DROP("MESSAGE_CONTENT_BKP");
ALTER TABLE "CART_REQUEST_TOOL"."EXTEND_VENDOR_REQUEST_MESSAGE" DROP("MESSAGE_CONTENT_BKP");
ALTER TABLE "CART_REQUEST_TOOL"."VENDOR_REQUEST_MESSAGE" DROP("MESSAGE_CONTENT_BKP");
ALTER TABLE "CART_REQUEST_TOOL"."VENDOR_INQUIRY_MESSAGE" DROP("MESSAGE_CONTENT_BKP");
ALTER TABLE "CART_REQUEST_TOOL"."INQUIRY_MESSAGE" DROP("MESSAGE_CONTENT_BKP");
ALTER TABLE "CART_REQUEST_TOOL"."REQUEST_MESSAGE" DROP("MESSAGE_CONTENT_BKP");

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT) 
VALUES('V2.0.0-40', 'Drop unused MESSAGE_CONTENT_BKP column', 'V201704251540__Drop_unused_column.sql');

COMMIT;