ALTER TABLE "CART_REQUEST_TOOL"."NEWS" ADD (DISPLAY_CREATED_DATE TIMESTAMP);

UPDATE "NEWS" SET DISPLAY_CREATED_DATE = CREATED_DATE_TZ;

ALTER TABLE "CART_REQUEST_TOOL"."NEWS" ALTER (DISPLAY_CREATED_DATE TIMESTAMP NOT NULL);

-- *************************************************************************************
-- Update schema version

INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT) 
VALUES('V2.0.0-62', 'Add DISPLAY_CREATED_DATE', 'V201710061310__Alter_news');

COMMIT;