-- *************************************************************************************
-- Update budget convertion rate for Cart Requests 2017 - Budget Year Id = 1

UPDATE "CART_REQUEST_TOOL"."SERVICE" SV
SET SV.BUDGET = (SV.AMOUNT / (SELECT CUR.CONVERSION_RATE FROM "CART_REQUEST_TOOL"."CURRENCY" CUR WHERE CUR.CURRENCY_ID = SV.CURRENCY_ID)) / 1000
WHERE (SELECT BUDGET_YEAR_ID FROM "CART_REQUEST_TOOL"."REQUEST" RQ WHERE RQ.REQUEST_ID = SV.REQUEST_ID) = 1 AND SV.ENABLED = 1;

UPDATE "CART_REQUEST_TOOL"."SPECIAL_REQUEST" SR
SET SR.BUDGET = (SR.AMOUNT / (SELECT CUR.CONVERSION_RATE FROM "CART_REQUEST_TOOL"."CURRENCY" CUR WHERE CUR.CURRENCY_ID = SR.CURRENCY_ID)) / 1000
WHERE (SELECT BUDGET_YEAR_ID FROM "CART_REQUEST_TOOL"."REQUEST" RQ WHERE RQ.REQUEST_ID = SR.REQUEST_ID) = 1 AND SR.ENABLED = 1;

UPDATE "CART_REQUEST_TOOL"."REQUEST_RISK_FUNDED" RRF
SET RRF.AMOUNT_KEUR = (RRF.AMOUNT / (SELECT CUR.CONVERSION_RATE FROM "CART_REQUEST_TOOL"."CURRENCY" CUR WHERE CUR.CURRENCY_ID = RRF.CURRENCY_ID)) / 1000
WHERE (SELECT BUDGET_YEAR_ID FROM "CART_REQUEST_TOOL"."REQUEST" RQ WHERE RQ.REQUEST_ID = RRF.REQUEST_ID) = 1 AND RRF.ENABLED = 1;

UPDATE "CART_REQUEST_TOOL"."REQUEST_SERVICE" RS
SET RS.TOTAL_BUDGET = (RS.CART_AMOUNT / (SELECT CUR.CONVERSION_RATE FROM "CART_REQUEST_TOOL"."CURRENCY" CUR WHERE CUR.CURRENCY_ID = RS.CURRENCY_ID)) / 1000
WHERE (SELECT BUDGET_YEAR_ID FROM "CART_REQUEST_TOOL"."REQUEST" RQ WHERE RQ.REQUEST_ID = RS.REQUEST_ID) = 1 AND RS.ENABLED = 1;

-- *************************************************************************************
-- Update schema version

INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V2.0.0-76', 'Update budget convertion rate for Cart Requests 2017', 'V201801121050__Update_cart_request_2017_budget.sql');

COMMIT;