/* Create table: VENDOR_CONTACT_INFORMATION */
create column table "CART_REQUEST_TOOL".VENDOR_CONTACT_INFORMATION
(
	vendor_contact_information_id bigint not null primary key generated by default as IDENTITY,
	vendor_id bigint not null,
	name nvarchar(255) not null,
	phone nvarchar(255),
	email nvarchar(255) not null,
	default_contact_information tinyint default 0,
	
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
    enabled tinyint default 1, 
	deleted tinyint default 0,
	
	FOREIGN KEY (vendor_id) REFERENCES VENDOR(vendor_id)
);

/* Add permissions to Create/Edit & Delete */
insert into "CART_REQUEST_TOOL"."PERMISSION_SERVICE"(PERMISSION_SERVICE_ID, SERVICE_NAME, PERMISSION_ID, RESOURCE_ID,CREATED_USER_ID) values(180,'vendorContactInformationService',9,1,1);
insert into "CART_REQUEST_TOOL"."PERMISSION_SERVICE"(PERMISSION_SERVICE_ID, SERVICE_NAME, PERMISSION_ID, RESOURCE_ID,CREATED_USER_ID) values(181,'vendorContactInformationService',9,6,1);
insert into "CART_REQUEST_TOOL"."PERMISSION_SERVICE"(PERMISSION_SERVICE_ID, SERVICE_NAME, PERMISSION_ID, RESOURCE_ID,CREATED_USER_ID) values(182,'vendorContactInformationService',10,6,1);
insert into "CART_REQUEST_TOOL"."PERMISSION_SERVICE"(PERMISSION_SERVICE_ID, SERVICE_NAME, PERMISSION_ID, RESOURCE_ID,CREATED_USER_ID) values(183,'vendorContactInformationService',11,6,1);

/* Alter REQUEST table to support one VENDOR_CONTACT_INFORMATION */
alter table "CART_REQUEST_TOOL"."REQUEST" add ("VENDOR_CONTACT_INFORMATION_ID" BIGINT null);
  
  -- *************************************************************************************
-- Update schema version

INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT) 
VALUES('V2.0.0-23', 'Create VENDOR CONTACT INFORMATION Table, Add permissions, add column in Request table', 'V201702171750__Create_Vendor_contact_information.sql');

COMMIT;
