-- *************************************************************************************
-- Insert Budget year 2019 and set as default

UPDATE "CART_REQUEST_TOOL"."BUDGET_YEAR" SET DEFAULT_YEAR = 0;
INSERT INTO "CART_REQUEST_TOOL"."BUDGET_YEAR"(BUDGET_YEAR_ID, BUDGET_YEAR, START_DATE, END_DATE, DEFAULT_YEAR, DESCRIPTION, CREATED_USER_ID, NEW_CART_REQUEST_ENABLED) VALUES (5, 2019, TO_TIMESTAMP('01-01-2019', 'DD-MM-YYYY'), TO_TIMESTAMP('31-12-2019', 'DD-MM-YYYY'), 1, 'Budget Year for 2019', 1, 1);

-- *************************************************************************************
-- Insert HL2 for budget year 2019

INSERT INTO "CART_REQUEST_TOOL"."HL2"(HL2_ID, ACRONYM, BUDGET_YEAR_ID, CREATED_USER_ID, TEAM_TYPE_ID) VALUES (4, 'XM', 5, 1, 1);

-- *************************************************************************************
-- Insert HL3 for budget year 2019

INSERT INTO "CART_REQUEST_TOOL"."HL3"(HL3_ID, HL3_DESCRIPTION, HL2_ID, CREATED_USER_ID, ACRONYM) VALUES (32, 'Business Management / Infrastructure', 4, 1, 'BMT');
INSERT INTO "CART_REQUEST_TOOL"."HL3"(HL3_ID, HL3_DESCRIPTION, HL2_ID, CREATED_USER_ID, ACRONYM) VALUES (33, 'GB Internal / External Communiations', 4, 1, 'GBC');
INSERT INTO "CART_REQUEST_TOOL"."HL3"(HL3_ID, HL3_DESCRIPTION, HL2_ID, CREATED_USER_ID, ACRONYM) VALUES (34, 'Commercial Sales Marketing', 4, 1, 'GCS');
INSERT INTO "CART_REQUEST_TOOL"."HL3"(HL3_ID, HL3_DESCRIPTION, HL2_ID, CREATED_USER_ID, ACRONYM) VALUES (35, 'Indirect Channel', 4, 1, 'GIC');
INSERT INTO "CART_REQUEST_TOOL"."HL3"(HL3_ID, HL3_DESCRIPTION, HL2_ID, CREATED_USER_ID, ACRONYM) VALUES (36, 'GB Strategic Initiatives', 4, 1, 'GMM');

-- *************************************************************************************
-- Assign the new teams to users

INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (32, 2, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (32, 1, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (32, 3, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (32, 4, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (32, 5, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (32, 10, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (32, 11, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (33, 2, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (33, 1, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (33, 3, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (33, 4, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (33, 5, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (33, 10, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (33, 11, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (34, 2, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (34, 1, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (34, 3, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (34, 4, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (34, 5, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (34, 10, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (34, 11, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (35, 2, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (35, 1, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (35, 3, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (35, 4, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (35, 5, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (35, 10, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (35, 11, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (36, 2, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (36, 1, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (36, 3, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (36, 4, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (36, 5, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (36, 10, 1);
INSERT INTO "CART_REQUEST_TOOL"."HL3_USER"(HL3_ID, USER_ID, CREATED_USER_ID) VALUES (36, 11, 1);

-- *************************************************************************************
-- Update schema version

INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V2.0.0-96', 'Inserted teams for budget year 2019', 'V201903261145__Insert_teams_for_2019.sql');

COMMIT;