CREATE COLUMN TABLE "CART_REQUEST_TOOL".CRT_RETURN_TYPE
(
	CRT_TYPE_ID BIGINT NOT NULL,
	RETURN_TYPE_ID BIGINT NOT NULL,
	
	CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE_TZ TIMESTAMP,
	CREATED_USER_ID BIGINT NOT NULL,
	MODIFIED_USER_ID BIGINT,
	ENABLED TINYINT DEFAULT 1, 
	DELETED TINYINT DEFAULT 0
);
ALTER TABLE "CART_REQUEST_TOOL"."CRT_RETURN_TYPE" ADD FOREIGN KEY ( "CRT_TYPE_ID" ) REFERENCES "CART_REQUEST_TOOL"."CRT_TYPE" ("CRT_TYPE_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;
ALTER TABLE "CART_REQUEST_TOOL"."CRT_RETURN_TYPE" ADD FOREIGN KEY ( "RETURN_TYPE_ID" ) REFERENCES "CART_REQUEST_TOOL"."RETURN_TYPE" ("RETURN_TYPE_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;